name: Generate Sphinx to gh-pages

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Sphinx Build
      run: |
        source venv/bin/activate
        make html
